feat(github-environments)

diff --git a/.github/workflows/push_preview.yml b/.github/workflows/push_preview.yml
--- a/.github/workflows/push_preview.yml
+++ b/.github/workflows/push_preview.yml
@@ -104,7 +104,7 @@ jobs:
               ![Coverage GIF](https://i.giphy.com/XIqCQx02E1U9W.webp)`
             });
 
-      - name: Create .env file from GitHub link
+      - name: Create .env file from GitHub raw file link
         env:
           GH_TOKEN: ${{ secrets.WF_GITHUB_TOKEN }}
           GH_LINK_PR_PROJECT_ENVS: ${{ secrets.GH_LINK_PR_PROJECT_ENVS }}
@@ -117,14 +117,25 @@ jobs:
             exit 1
           fi
       
-          echo "📥 $LINK"
+          if [[ "$LINK" == *"?"* ]]; then
+            AUTH_LINK="${LINK}&token=${GH_TOKEN}"
+          else
+            AUTH_LINK="${LINK}?token=${GH_TOKEN}"
+          fi
       
-          curl -H "Authorization: token $GH_TOKEN" \
-                -H "Accept: application/vnd.github.v3.raw" \
-                "$LINK" > .env
+          echo "📥 Downloading .env from: $AUTH_LINK"
+      
+          CONTENT=$(curl -sSL "$AUTH_LINK")
+      
+          if [ -z "$CONTENT" ]; then
+            echo "❌ Failed to download content or content is empty."
+            exit 1
+          fi
+
+          printf "%s" "$CONTENT" > .env
       
           echo "✅ File .env created:"
-        
+          
       - name: Build project
         run: |
           export NODE_OPTIONS="--max-old-space-size=4096"
